name: flutter_signin
description: "Learn Flutter Project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  http: any
  protobuf: ^3.1.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  socket_io_client: ^2.0.3+1
  flutter_staggered_animations: ^1.1.1
  audioplayers: ^6.1.0
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.0
  mobx_codegen: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
